<a href="https://colab.research.google.com/github/orin00/colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 넘파이 모듈 불러오기, as는 별칭을 붙이겠다는 의미(numpy는 무조건 np가 별칭)
import numpy as np

In [ ]:
num = [1,2,3,4,5,6,7,8,9]
result = num + [3]
result

[1, 2, 3, 4, 5, 6, 7, 8, 9, 3]

In [ ]:
num + 3

TypeError: can only concatenate list (not "int") to list

In [ ]:
arr = np.array(num)
arr + np.array([3])
# arr + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
new_num = []
for i in num:
  new_num.append(i+3)
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
# 리스트 컴플레이션
new_num = [i+3 for i in num]
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
# list의 반복문 수행 시간 측정
import time # 시간 재는 기능

num = range(10000)
result = []
start = time.time()
for i in num:
  i += 3
  result.append(i)
end = time.time()
sec = (end - start) * 1000
print(f"{sec: .4f} sec")
print(result[-5:])

 1.9195 sec
[9998, 9999, 10000, 10001, 10002]


In [ ]:
# numpy를 사용한 수행시간
import time
import numpy as np

num = np.arange(10000)
start = time.time()
result = num + 3
end = time.time()
sec = (end - start) * 1000
print(f"{sec: .4f} sec")
print(result[-5:])

 0.1512 sec
[ 9998  9999 10000 10001 10002]


In [ ]:
text = ['I','Love','Python']
text2 = ['(나)','(좋아해)','(파이썬)']

result = text + text2
result

['I', 'Love', 'Python', '(나)', '(좋아해)', '(파이썬)']

In [ ]:
# numpy는 리스트의 각 항목들을 결합시킨다는 느낌
import numpy as np

arr_str = np.array(['I','Love','Python'],dtype=object)
arr_str2 = np.array(['(나)','(좋아해)','(파이썬)'])

result = arr_str + arr_str2
result

array(['I(나)', 'Love(좋아해)', 'Python(파이썬)'], dtype=object)

In [ ]:
import numpy as np
arr = np.array([[1,2]])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array([[0,0,0],
								[1,1,1]])
print(arr.ndim) # 차원수
print(arr.shape) # array의 모양
print(type(arr)) # class
print(arr.dtype) # 요소들의 Type

2
(2, 3)
<class 'numpy.ndarray'>
int64


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([2])
print(a*b)
print(a*c)
print(a*b == a*c)

[2 4 6]
[2 4 6]
[ True  True  True]


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a * 2)

[2 4 6]


In [ ]:
import numpy as np

arr = np.array([1,2,3])
arr2 = np.array([1,2,3], float)
print(arr.dtype, arr2.dtype)
arr.astype(float)

int64 float64


array([1., 2., 3.])

In [ ]:
arr2 = arr2.astype("int64")

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
zer = np.zeros(2)
zer2 = np.zeros((3,2))
zer3 = np.zeros((2,3,2))
print(zer)
print('--------------------')
print(zer2)
print('--------------------')
print(zer3)

[0. 0.]
--------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
one = np.ones(2)
one2 = np.ones((3,2))
one3 = np.ones((2,3,2))
print(one )
print('--------------------')
print(one2 )
print('--------------------')
print(one3 )

[1. 1.]
--------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
ful = np.full((2),5)
ful2 = np.full((2,3),5)
ful3 = np.full((2,3,4), 'full')
print(ful)
print('--------------------')
print(ful2)
print('--------------------')
print(ful3 )

[5 5]
--------------------
[[5 5 5]
 [5 5 5]]
--------------------
[[['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']]

 [['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']]]


In [ ]:
arn = np.arange(8)
arn2 = np.arange(2,4) # 시작, 끝
arn3 = np.arange(5,10,2)
print(arn)
print('--------------------')
print(arn2)
print('--------------------')
print(arn3)

[0 1 2 3 4 5 6 7]
--------------------
[2 3]
--------------------
[5 7 9]


In [ ]:
lin = np.arange(2,8)
lin2 = np.linspace(3,7,10)

print(lin)
print('--------------------')
print(lin2)

[2 3 4 5 6 7]
--------------------
[3.         3.44444444 3.88888889 4.33333333 4.77777778 5.22222222
 5.66666667 6.11111111 6.55555556 7.        ]


In [ ]:
iden = np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
eye = np.eye(3)
eye2 = np.eye(3,k=1)
eye3 = np.eye(3,5)

print(eye)
print('--------------------')
print(eye2)
print('--------------------')
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
import numpy as np

arr = np.array([1,2,3])

print(arr[1])
print(arr[0:2])
print(arr[1:])
print(arr[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
li = [[1,2,3], [4,5,6]]
li[0][1:]

[2, 3]

In [ ]:
arr = np.array(li)
print(arr[0][1:])
print(arr[0,:1])

[2 3]
[1]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
result = []
for i in arr:
  if i%2 == 0:
    result.append(i);
result

[2, 4, 6, 8, 10, 12]

In [ ]:
from re import A
arr = [[2,1,3,4],[7,6,8,5],[9,10,11,12]]
result = []
for i in arr:
  for j in i:
    if j%2 == 0:
      result.append(j)
result

[2, 4, 6, 8, 10, 12]

In [ ]:
li = [1,3,5,4,6,7,2,8,9,10,11,12]
arr = np.array(li)
arr[arr%2==0]

array([ 4,  6,  2,  8, 10, 12])

In [ ]:
li = [[2,1,3,6],[7,4,8,5],[9,10,11,12]]
arr = np.array(li)
arr[arr%2==0]

array([ 2,  6,  4,  8, 10, 12])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.reshape(12,)

array([ 2,  1,  3,  6,  7,  4,  8,  5,  9, 10, 11, 12])

In [ ]:
# arr.resize(5,5,refcheck=False)
# arr

array([[ 2,  1,  3,  6,  7],
       [ 4,  8,  5,  9, 10],
       [11, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
arr.reshape(3,2,-1)

array([[[ 2,  1],
        [ 3,  6]],

       [[ 7,  4],
        [ 8,  5]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
zr = np.zeros((2,3,4,5))
zr.shape

(2, 3, 4, 5)

In [ ]:
zr.T.shape #전치행렬

(5, 4, 3, 2)

In [ ]:
zr.transpose(0,3,1,2).shape #내가 변경하고자 하는 순서를 지정할 수 있다.

(2, 5, 3, 4)

In [ ]:
zr.swapaxes(3,1).shape # 내가 원하는 축 2개만 서로 변경할 때 사용

(2, 5, 4, 3)

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

a + b

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c = np.array([[5], [6]])
np.concatenate((a,c), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
s = np.array([[1,2],[3,4],[5,6]])
s

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
s.sum()

21

In [ ]:
s.sum(axis=0)

array([ 9, 12])

In [ ]:
s.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
import numpy as np

arr = np.array(np.arange(1,11))

print(arr)
print(arr.sum())
print(arr.cumsum())

[ 1  2  3  4  5  6  7  8  9 10]
55
[ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print('---------------')
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[ 7  9 11 13 15]
[15 40]
---------------
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]]


In [ ]:
import numpy as np
arr = np.array(np.random.randint(1,10,5))
print(arr)
print(arr.min())
print(arr.max())

[9 8 4 5 1]
1
9


In [ ]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.min(axis=0))
print(arr.min(axis=1))
print('---------------')
print(arr.max(axis=0))
print(arr.max(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[1 2 3 4 5]
[1 6]
---------------
[ 6  7  8  9 10]
[ 5 10]


In [ ]:
import numpy as np

arr = np.array([1,2,3,2,2,4,5,5,5])
np.unique(arr)
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5]), array([1, 3, 1, 1, 3]))

In [ ]:
arr = np.random.randint(1,10,6)
print(arr)
np.unique(arr)

[3 4 9 6 4 9]


array([3, 4, 6, 9])

In [ ]:
np.unique([1,1,2,3,4,6,2], return_counts=True)

(array([1, 2, 3, 4, 6]), array([2, 2, 1, 1, 1]))

In [ ]:
import numpy as np

arr = np.array([1,5,2,3,7,8,9,4])
arr_a = np.sort(arr)
arr_d = np.sort(arr)[::-1]
print(arr_a)
print(arr_d)

[1 2 3 4 5 7 8 9]
[9 8 7 5 4 3 2 1]


In [ ]:
arr = np.array([1,5,2,3,7,8,9,4]).reshape(2,4)

arr_c = np.sort(arr, axis=0)
arr_r = np.sort(arr, axis=1)

print(arr_c)
print(arr_r)

[[1 5 2 3]
 [7 8 9 4]]
[[1 2 3 5]
 [4 7 8 9]]


In [ ]:
np.random.choice(np.arange(1,11), size=5, replace=False)

array([9, 5, 1, 7, 3])