In [96]:
# RNN 구현하기 (numpy)
# one-to-many, many-to-one, many-to-many
import numpy as np

# 초기 상태 셋팅
timesteps = 10 # 시계열 데이터 크기 == 행 (학습 반복 횟수)
input_dim = 4 # 입력값의 크기 == 열
hidden_units = 8 # 은닉상태의 크기 == RNN셀의 용량, 메모리 셀의 갯수

# 입력 데이터 만들기
inputs = np.random.random((timesteps, input_dim))
inputs.shape # (10, 4)
inputs # 2차원 array

# 초기 은닉 상태를 설정
hidden_state_t = np.zeros((hidden_units,))
hidden_state_t

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
# 각각의 가중치와 편향 설정
wx = np.random.random((hidden_units, input_dim)) # 입력 데이터에 대한 가중치 행렬 (8, 4)
wh = np.random.random((hidden_units, hidden_units)) # 은닉 상태에 대한 가중치 행렬 (8, 8)
b = np.random.random((hidden_units,)) # 은닉 상태에 대한 편향(8,)
print(wx.shape, wh.shape, b.shape)

(8, 4) (8, 8) (8,)


In [98]:
total_hidden_states = []

# 각 timesteps별 입력 데이터
for input_t in inputs:
    # (wx * wh) + (wh * ht - 1) + b
    output_t = np.tanh(np.dot(wx, input_t) + np.dot(wh, hidden_state_t) + b)
    # print(output_t)
    # 각 timesteps 별 메모리셀의 (출력 크기는 8,),
    
    total_hidden_states.append(list(output_t))
    hidden_state_t = output_t
    
# 출력시 값을 깔끔하게 보기 위한 용도
total_hidden_states = np.stack(total_hidden_states, axis = 0)
print('모든 시점의 은닉 상태')
print(total_hidden_states)

모든 시점의 은닉 상태
[[0.79760423 0.69018171 0.83021879 0.85030391 0.91704176 0.9651071
  0.97895239 0.95402838]
 [0.9980681  0.99931814 0.99783413 0.99955278 0.99995499 0.99999376
  0.99995118 0.9999657 ]
 [0.99850159 0.99938663 0.99741734 0.99976645 0.99995719 0.99999664
  0.99996001 0.99996023]
 [0.99835267 0.99941748 0.9975796  0.99979104 0.99996029 0.99999704
  0.99996532 0.9999588 ]
 [0.99826831 0.99937549 0.99748538 0.99965354 0.99997165 0.99999679
  0.9999646  0.99995034]
 [0.99910859 0.99956051 0.99881928 0.99961449 0.99998472 0.99999719
  0.99996332 0.9999809 ]
 [0.99838925 0.99947249 0.99775475 0.99984264 0.99995917 0.99999747
  0.99997195 0.99996691]
 [0.99874936 0.99962392 0.9988734  0.9996609  0.99999056 0.99999825
  0.99998409 0.99998132]
 [0.99918156 0.9997182  0.9991848  0.99976074 0.99999219 0.99999865
  0.9999895  0.99999285]
 [0.99860819 0.99948911 0.99799446 0.99982412 0.99996321 0.99999736
  0.99996917 0.99997126]]


In [99]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(8, input_shape=(10, 4), return_sequences=True))

In [100]:
model.summary()

Model: "sequential_29"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_38 (SimpleRNN)            │ (None, 10, 8)               │             104 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 104 (416.00 B)

 Trainable params: 104 (416.00 B)

 Non-trainable params: 0 (0.00 B)

In [101]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(8, input_shape=(10, 4), return_sequences=True))
model.add(SimpleRNN(8, return_sequences=True))
model.add(SimpleRNN(8, return_sequences=True))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [102]:
model.summary()

Model: "sequential_30"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_39 (SimpleRNN)            │ (None, 10, 8)               │             104 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_40 (SimpleRNN)            │ (None, 10, 8)               │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_41 (SimpleRNN)            │ (None, 10, 8)               │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 10, 10)              │              90 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 466 (1.82 KB)

 Trainable params: 466 (1.82 KB)

 Non-trainable params: 0 (0.00 B)

In [251]:
## RNN 단어 생성기
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [252]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [253]:
print(text)

경마장에 있는 말이 뛰고 있다

그의 말이 법이다

가는 말이 고와야 오는 말이 곱다



In [254]:
tokenizer = Tokenizer() # 토크나이징 모듈 : 각 단어로 토큰화하는 작업
tokenizer.fit_on_texts([text]) # 토크나이저로 해당 text 토큰화
vocab_size = len(tokenizer.word_index) + 1  # 패딩을 고려하여 +1

print('단어 집합의 크기:', vocab_size)
print('단어 인덱스:', tokenizer.word_index)

단어 집합의 크기: 12
단어 인덱스: {'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [255]:
## 시계열 데이터 생성
sequences = []
# text.split('\n')
tokenizer.texts_to_sequences(['경마장에 있는 말이 뛰고 있다\n'])
for line in text.split('\n'):
    encoded = tokenizer.texts_to_sequences([line])[0] # 맵핑된 숫자로 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

len(sequences)

11

In [256]:
for j in sequences:
    print(len(j)) # 입력값을 6개로 맞춰야한다.

2
3
4
5
2
3
2
3
4
5
6


In [257]:
max_len = max(len(l) for l in sequences)
max_len

6

In [258]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [259]:
# X 데이터와 Y 데이터로 분리
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [260]:
y = to_categorical(y, num_classes=vocab_size)
y

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [261]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

model = Sequential()
model.add(Embedding(vocab_size, 10))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [262]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 2s - 2s/step - acc: 0.0909 - loss: 2.4852
Epoch 2/200
1/1 - 0s - 20ms/step - acc: 0.0909 - loss: 2.4704
Epoch 3/200
1/1 - 0s - 20ms/step - acc: 0.1818 - loss: 2.4560
Epoch 4/200
1/1 - 0s - 24ms/step - acc: 0.1818 - loss: 2.4417
Epoch 5/200
1/1 - 0s - 22ms/step - acc: 0.3636 - loss: 2.4274
Epoch 6/200
1/1 - 0s - 20ms/step - acc: 0.6364 - loss: 2.4129
Epoch 7/200
1/1 - 0s - 21ms/step - acc: 0.6364 - loss: 2.3981
Epoch 8/200
1/1 - 0s - 23ms/step - acc: 0.6364 - loss: 2.3828
Epoch 9/200
1/1 - 0s - 24ms/step - acc: 0.6364 - loss: 2.3669
Epoch 10/200
1/1 - 0s - 19ms/step - acc: 0.5455 - loss: 2.3503
Epoch 11/200
1/1 - 0s - 20ms/step - acc: 0.5455 - loss: 2.3329
Epoch 12/200
1/1 - 0s - 20ms/step - acc: 0.4545 - loss: 2.3146
Epoch 13/200
1/1 - 0s - 23ms/step - acc: 0.4545 - loss: 2.2952
Epoch 14/200
1/1 - 0s - 21ms/step - acc: 0.4545 - loss: 2.2748
Epoch 15/200
1/1 - 0s - 23ms/step - acc: 0.4545 - loss: 2.2533
Epoch 16/200
1/1 - 0s - 20ms/step - acc: 0.4545 - loss: 2.2307
Epo

In [263]:
model.summary()

Model: "sequential_33"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ (None, 5, 10)               │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_43 (SimpleRNN)            │ (None, 32)                  │           1,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 12)                  │             396 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,678 (22.18 KB)

 Trainable params: 1,892 (7.39 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 3,786 (14.79 KB)

In [284]:
def sentence_generator(model, tokenizer, current_word, n): # 단어 생성기
    init_word = current_word ## 입력받은 단어 -> init_word + 입력 단어
    sentence = '' ## 최종 문장 완성

    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0] # 내가 선택한 단어를 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 입력 데이터 크기

        result = model.predict(encoded) # 사전에 학습된 모델의 예측 결과
        result = np.argmax(result, axis=1) # 소프트 맥스니까 가장 높은 결과 선택

        for word, index in tokenizer.word_index.items(): # 내가 주어진 단어와 예측된 단어가 같으면 정지
            if index == result:
                break

        current_word = current_word + " " + word # 현재 단어에 계속 단어 추가
        sentence = sentence + " " + word # 모든 단어가 추가된 최종 결과
    
    sentence = init_word + sentence
    return sentence

In [291]:
print(sentence_generator(model, tokenizer, '경마장에', 4))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
경마장에 있는 말이 뛰고 있다


In [292]:
print(sentence_generator(model, tokenizer, '그의', 2))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
그의 말이 법이다


In [293]:
print(sentence_generator(model, tokenizer, '가는', 5))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
가는 말이 고와야 오는 말이 곱다
